LIB_SRC = 			\
	Acceptor.cc		\
	Channel.cc		\
	EventLoop.cc		\
	InetAddress.cc		\
	Poller.cc		\
	Socket.cc		\
	SocketOps.cc		\
	Timer.cc		\
	TimerQueue.cc
BINARIES = test7

all: $(BINARIES)

include ../reactor.mk

#test1: test1.cc
#test3: test3.cc
test7: test7.cc